name: clipseg-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - numpy
  - scipy
  - matplotlib-base
  - pip
  - pip:
    - --find-links https://download.pytorch.org/whl/torch_stable.html
    - torch==2.0.0
    - torchvision==0.15.1   
    - opencv-python
    - ipykernel
    - git+https://github.com/openai/CLIP.git
